// components/FormattedTime.vue
<template>
  <time :datetime="asAttribute">{{ asText }}</time>
</template>

<script lang="ts">
import Vue from 'vue'
import 'dayjs/plugin/timezone'

export default Vue.extend({
  name: 'FormattedTime',
  props: {
    datetime: {
      type: String,
      required: true,
    },
  },
  computed: {
    asAttribute() {
      return new Date(this.datetime).toISOString()
    },
    asText() {
      return this.$dayjs(this.datetime)
        .tz('Asia/Tokyo')
        .format('YYYY/MM/DD HH:mm')
    },
  },
})
</script>

// lib/components/FormattedTime.tsx
import { h } from 'preact'
import dayjs from 'dayjs'
import utc from 'dayjs/plugin/utc'
import timezone from 'dayjs/plugin/timezone'

dayjs.extend(utc)
dayjs.extend(timezone)
dayjs.tz.setDefault('Asia/Tokyo')

type Props = {
  datetime: Date
}

export const FormattedTime = ({ datetime }: Props) => {
  const day = dayjs.tz(datetime)
  const attr = day.format()
  const body = day.format('YYYY/MM/DD HH:mm')
  return <time dateTime={attr}>{body}</time>
}
